name: safe4all-climate-risk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - ipywidgets
  - geemap
  - earthengine-api
  - pandas
  - numpy
  - matplotlib
  - requests
  - xarray
  - netcdf4
  - pip
