name: safe4all-climate-risk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - ipywidgets
  - geemap
  - earthengine-api
  - geopandas
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - folium
  - plotly
  - requests
  - xarray
  - netcdf4
  - rioxarray
  - scipy
  - scikit-learn
  - tqdm
  - pip
